import { useMemo, useState } from 'react';
import { Printer, Download, FileText } from 'lucide-react';
import { useData } from '../context/DataContext';
import PageHeader from '../components/common/PageHeader';
import { filterByDateRange, sumBy } from '../utils/calculations';
import {
  formatCurrency,
  formatDate,
  formatKg,
  todayISO,
  daysAgoISO,
} from '../utils/formatters';

const REPORT_TYPES = [
  { label: 'Daily Report', days: 0 },
  { label: '7 Day Report', days: 7 },
  { label: '10 Day Report', days: 10 },
  { label: 'Monthly Report', days: 30 },
  { label: 'Yearly Report', days: 365 },
];

export default function Reports() {
  const { stock, production, delivery, expenses } = useData();
  const [type, setType] = useState('Daily Report');

  const option = REPORT_TYPES.find((r) => r.label === type) || REPORT_TYPES[0];
  const from = option.days === 0 ? todayISO() : daysAgoISO(option.days);
  const to = todayISO();

  const data = useMemo(() => {
    const prod = filterByDateRange(production, from, to);
    const del = filterByDateRange(delivery, from, to);
    const exp = filterByDateRange(expenses, from, to);

    const wheatUsed = sumBy(prod, 'wheatUsed');
    const atta = sumBy(prod, 'atta');
    const maida = sumBy(prod, 'maida');
    const bhusi = sumBy(prod, 'bhusi');
    const loss = sumBy(prod, 'loss');
    const totalOutput = atta + maida + bhusi;
    const efficiency = wheatUsed
      ? Math.round((totalOutput / wheatUsed) * 1000) / 10
      : 0;

    const delAtta = sumBy(del.filter((d) => d.product === 'Atta'), 'quantity');
    const delMaida = sumBy(del.filter((d) => d.product === 'Maida'), 'quantity');
    const delBhusi = sumBy(del.filter((d) => d.product === 'Bhusi'), 'quantity');
    const delWheat = sumBy(del.filter((d) => d.product === 'Wheat'), 'quantity');
    const totalDelivery = delAtta + delMaida + delBhusi + delWheat;

    const opening = stock.reduce((acc, s) => acc + (s.opening || 0), 0);
    const closing = opening + totalOutput - totalDelivery;

    const totalExpense = sumBy(exp, 'amount');

    return {
      wheatUsed,
      atta,
      maida,
      bhusi,
      loss,
      totalOutput,
      efficiency,
      delAtta,
      delMaida,
      delBhusi,
      delWheat,
      totalDelivery,
      opening,
      closing,
      totalExpense,
    };
  }, [production, delivery, expenses, stock, from, to]);

  const handlePrint = () => window.print();

  const handleExportCSV = () => {
    const rows = [
      ['Yusuf Flowers Mills LTD', ''],
      ['Demra, Dhaka', ''],
      ['Report', type],
      ['From', from],
      ['To', to],
      [],
      ['Metric', 'Value'],
      ['Opening Stock (KG)', data.opening],
      ['Wheat Used (KG)', data.wheatUsed],
      ['Atta Produced (KG)', data.atta],
      ['Maida Produced (KG)', data.maida],
      ['Bhusi Produced (KG)', data.bhusi],
      ['Total Production (KG)', data.totalOutput],
      ['Atta Delivered (KG)', data.delAtta],
      ['Maida Delivered (KG)', data.delMaida],
      ['Bhusi Delivered (KG)', data.delBhusi],
      ['Total Delivery (KG)', data.totalDelivery],
      ['Closing Stock (KG)', data.closing],
      ['Loss (KG)', data.loss],
      ['Efficiency (%)', data.efficiency],
      ['Total Expense', data.totalExpense],
      [],
      ['Generated by', 'Yusuf Flowers Mills LTD Management System'],
      ['Developed by', 'Onexero — onexero.netlify.app'],
    ];
    const csv = rows.map((r) => r.join(',')).join('\n');
    const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${type.replace(/\s+/g, '_')}_${to}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportPDF = () => window.print();

  return (
    <>
      <PageHeader
        title="Reports"
        subtitle="Generate and export business reports"
        actions={
          <div className="flex flex-wrap items-center gap-2 no-print">
            <button className="btn-secondary" onClick={handlePrint}>
              <Printer size={15} /> Print
            </button>
            <button className="btn-secondary" onClick={handleExportCSV}>
              <Download size={15} /> CSV
            </button>
            <button className="btn-primary" onClick={handleExportPDF}>
              <FileText size={15} /> PDF
            </button>
          </div>
        }
      />

      <div className="card p-4 mb-4 no-print flex flex-wrap gap-1.5">
        {REPORT_TYPES.map((r) => (
          <button
            key={r.label}
            onClick={() => setType(r.label)}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${
              type === r.label
                ? 'bg-brand-600 text-white border-brand-600'
                : 'bg-white text-slate-600 border-slate-200 hover:bg-slate-50'
            }`}
          >
            {r.label}
          </button>
        ))}
      </div>

      <div className="card p-6 print-area">
        <div className="flex items-start justify-between border-b border-slate-100 pb-4 mb-5">
          <div>
            <h2 className="text-lg font-semibold text-slate-900">
              Yusuf Flowers Mills LTD
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">Demra, Dhaka</p>
            <p className="text-sm text-slate-500 mt-1">{type}</p>
          </div>
          <div className="text-right text-sm">
            <p className="text-slate-500">From</p>
            <p className="font-medium text-slate-800">{formatDate(from)}</p>
            <p className="text-slate-500 mt-1">To</p>
            <p className="font-medium text-slate-800">{formatDate(to)}</p>
          </div>
        </div>

        <Section title="Opening Stock">
          <Row label="Opening Stock" value={formatKg(data.opening)} />
        </Section>

        <Section title="Production">
          <Row label="Wheat Used" value={formatKg(data.wheatUsed)} />
          <Row label="Atta Produced" value={formatKg(data.atta)} />
          <Row label="Maida Produced" value={formatKg(data.maida)} />
          <Row label="Bhusi Produced" value={formatKg(data.bhusi)} />
          <Row label="Total Production" value={formatKg(data.totalOutput)} highlight />
          <Row label="Loss" value={formatKg(data.loss)} />
          <Row label="Efficiency" value={`${data.efficiency}%`} />
        </Section>

        <Section title="Delivery">
          <Row label="Atta Delivered" value={formatKg(data.delAtta)} />
          <Row label="Maida Delivered" value={formatKg(data.delMaida)} />
          <Row label="Bhusi Delivered" value={formatKg(data.delBhusi)} />
          <Row label="Total Delivery" value={formatKg(data.totalDelivery)} highlight />
        </Section>

        <Section title="Closing">
          <Row label="Closing Stock" value={formatKg(data.closing)} highlight />
          <Row label="Total Expense" value={formatCurrency(data.totalExpense)} />
        </Section>

        
        <div className="border-t border-slate-100 pt-4 mt-6 flex items-center justify-between text-[11px] text-slate-400">
          <span>Generated by Yusuf Flowers Mills LTD Management System</span>
          <span>
            Developed by{' '}
            <a
              href="https://onexero.netlify.app"
              target="_blank"
              rel="noreferrer"
              className="text-brand-600 hover:underline"
            >
              Onexero
            </a>
          </span>
        </div>
      </div>
    </>
  );
}

function Section({ title, children }) {
  return (
    <div className="mb-5">
      <h3 className="text-xs uppercase tracking-wide text-slate-500 font-semibold mb-2">
        {title}
      </h3>
      <div className="divide-y divide-slate-50">{children}</div>
    </div>
  );
}

function Row({ label, value, highlight }) {
  return (
    <div className="flex items-center justify-between py-2">
      <span
        className={`text-sm ${
          highlight ? 'font-semibold text-slate-900' : 'text-slate-600'
        }`}
      >
        {label}
      </span>
      <span
        className={`text-sm ${
          highlight ? 'font-semibold text-brand-700' : 'text-slate-800'
        }`}
      >
        {value}
      </span>
    </div>
  );
}